In [22]:
import pandas as pd
import altair as alt

In [23]:
df = pd.read_csv("kdramas_database_limpia.csv", delimiter=",", encoding="UTF-8")

In [24]:
df.shape

(350, 8)

In [25]:
df.columns

Index(['title', 'release_year', 'episodes', 'ratings', 'netflix', 'viki',
       'prime_video', 'disney_plus'],
      dtype='object')

In [26]:
df["title"].head(11)

0     When Life Gives You Tangerines
1               Twinkling Watermelon
2                Hospital Playlist 2
3                   Alchemy of Souls
4               Crash Landing on You
5                 The Flower of Evil
6         Under The Queen's Umbrella
7                             Moving
8                      Lovely Runner
9                    Prison Playbook
10                         My Mister
Name: title, dtype: object

In [27]:
df.sort_values("ratings", ascending=False).head(10)

,title,release_year,episodes,ratings,netflix,viki,prime_video,disney_plus
0,When Life Gives You Tangerines,2025,16,9.3,yes,no,no,no
1,Twinkling Watermelon,2023,16,9.2,yes,yes,no,no
2,Hospital Playlist 2,2021,12,9.1,yes,no,no,no
3,Alchemy of Souls,2022,20,9.1,yes,no,no,no
5,The Flower of Evil,2020,16,9.0,yes,yes,no,no
6,Under The Queen's Umbrella,2022,16,9.0,yes,no,no,no
8,Lovely Runner,2024,16,9.0,yes,yes,no,no
4,Crash Landing on You,2019,16,9.0,yes,no,no,no
7,Moving,2023,20,9.0,no,no,no,yes
14,The Glory Part 2,2023,8,8.9,yes,no,no,no

In [28]:
top_kdramas = df.sort_values(by="ratings", ascending=False)

In [29]:
top_100 = top_kdramas.head(100)

In [30]:
conteo_plataformas = {
    "Netflix": (top_100["netflix"] == "yes").sum(),
    "Viki": (top_100["viki"] == "yes").sum(),
    "Prime Video": (top_100["prime_video"] == "yes").sum(),
    "Disney+": (top_100["disney_plus"] == "yes").sum()
}

In [31]:
conteo_df = pd.DataFrame({
    "Platform": conteo_plataformas.keys(),
    "Cantidad": conteo_plataformas.values()
})

In [33]:
alt.Chart(conteo_df).mark_bar().encode(
    x=alt.X('Platform', sort=None, title='Plataforma'),
    y=alt.Y('Cantidad', title='Número de KDramas'),
    color=alt.Color('Platform', scale=alt.Scale(
        domain=['Netflix', 'Viki', 'Prime Video', 'Disney+'],
        range=['red', 'green', 'lightblue', 'blue']
    ), legend=alt.Legend(title='Plataforma')),
    tooltip=['Platform', 'Cantidad']
).properties(
    title='Número de KDramas por Plataforma en el Top 100'
)

alt.Chart(...)

In [35]:
chart_to_save = alt.Chart(conteo_df).mark_bar().encode(
    x=alt.X('Platform', sort=None, title='Plataforma'),
    y=alt.Y('Cantidad', title='Número de KDramas'),
    color=alt.Color('Platform', scale=alt.Scale(
        domain=['Netflix', 'Viki', 'Prime Video', 'Disney+'],
        range=['red', 'green', 'lightblue', 'blue']
    ), legend=alt.Legend(title='Plataforma')),
    tooltip=['Platform', 'Cantidad']
).properties(
    title='Número de KDramas por Plataforma en el Top 100'
)

chart_to_save.save('numero_kdramas_por_plataforma.html')